# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/?ordering=id
Content-Type: application/json
Authorization: Token 3921ef21462cfa0269a3d41ab2512f9097dcd514

###

# получение объявлений по id
GET {{baseUrl}}/advertisements/15
Content-Type: application/json
Authorization: Token 3921ef21462cfa0269a3d41ab2512f9097dcd514

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 8782b9516172793cc8aa58e2a47349fb9bfc5042

{
  "title": "Объявление 24",
  "description": "Срочно"
}

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 8782b9516172793cc8aa58e2a47349fb9bfc5042

{
  "title": "Ноутбук продам",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/6/
Content-Type: application/json
Authorization: Token 3921ef21462cfa0269a3d41ab2512f9097dcd514

{
  "status": "CLOSED"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/24/
Content-Type: application/json
Authorization: Token 8782b9516172793cc8aa58e2a47349fb9bfc5042

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json
Authorization: Token 8782b9516172793cc8aa58e2a47349fb9bfc5042

###

# сортировка по создателю
GET {{baseUrl}}/advertisements/?ordering=creator
Content-Type: application/json

###

# сортировка по создателю обратная
GET {{baseUrl}}/advertisements/?ordering=-created_at
Authorization: Token 3921ef21462cfa0269a3d41ab2512f9097dcd514
###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2025-06-24&ordering=id
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_after=2025-06-26&ordering=id
Content-Type: application/json
Authorization: Token 8782b9516172793cc8aa58e2a47349fb9bfc5042

###

# удаление объявления
DELETE {{baseUrl}}/advertisements/15/
Content-Type: application/json
Authorization: Token 3921ef21462cfa0269a3d41ab2512f9097dcd514

###

# просмотр списка Избранных
GET {{baseUrl}}/advertisements/getfavorits/
Content-Type: application/json
Authorization: Token 8782b9516172793cc8aa58e2a47349fb9bfc5042

###

# добавление в список Избранных
POST {{baseUrl}}/advertisements/27/makefavorits/
Content-Type: application/json
Authorization: Token 8782b9516172793cc8aa58e2a47349fb9bfc5042

###

# добавление в список Избранных
POST {{baseUrl}}/advertisements/44/makefavorits/
Content-Type: application/json
Authorization: Token 3921ef21462cfa0269a3d41ab2512f9097dcd514

###

# удаление из списка Избранных
DELETE {{baseUrl}}/advertisements/5/delfavorits/
Content-Type: application/json
Authorization: Token 8782b9516172793cc8aa58e2a47349fb9bfc5042
