# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 8782b9516172793cc8aa58e2a47349fb9bfc5042

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 8782b9516172793cc8aa58e2a47349fb9bfc5042

{
  "title": "Ноутбук продам",
  "description": "Срочно"
}

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
Authorization: Token 3921ef21462cfa0269a3d41ab2512f9097dcd514

{
  "title": "Куплю диван",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token 3921ef21462cfa0269a3d41ab2512f9097dcd514

{
  "status": "CLOSED"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/4/
Content-Type: application/json
Authorization: Token 8782b9516172793cc8aa58e2a47349fb9bfc5042

{
  "status": "OPEN"
}

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=1
Content-Type: application/json

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?search=ноут&ordering=id
Content-Type: application/json

###

GET {{baseUrl}}/advertisements/?ordering=id

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2025-06-25
Content-Type: application/json

###

DELETE {{baseUrl}}/advertisements/14/
Content-Type: application/json
Authorization: Token 3921ef21462cfa0269a3d41ab2512f9097dcd514
