# Generated by Django 5.2.3 on 2025-06-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_alter_advertisement_options_alter_advertisement_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favorites',
            old_name='advertisementa',
            new_name='advertisement',
        ),
    ]
