# Generated by Django 5.2.3 on 2025-06-17 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="sensor_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="measurement.sensor"
            ),
        ),
    ]
