# Generated by Django 5.2.3 on 2025-06-17 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0003_alter_measurement_sensor_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="measurement",
            old_name="sensor_id",
            new_name="sensor",
        ),
    ]
