# Generated by Django 5.2.3 on 2025-06-17 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0004_rename_sensor_id_measurement_sensor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="sensor",
            field=models.IntegerField(),
        ),
    ]
