# Generated by Django 5.2.3 on 2025-06-17 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("measurement", "0005_alter_measurement_sensor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="measurement",
            name="sensor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="measurement",
                to="measurement.sensor",
            ),
        ),
    ]
