# примеры API-запросов

@baseUrl = http://localhost:8000/api


# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик на кухне за холодильником"
}

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик в спальне"
}

###

# создание датчика
POST {{baseUrl}}/sensors/
Content-Type: application/json

{
  "name": "ESP32",
  "description": "Датчик в гостинной"
}

###

# обновление датчика
PATCH {{baseUrl}}/sensors/15/
Content-Type: application/json

{
  "description": "Перенес датчик на балкон"
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 17,
  "temperature": 22.3
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 17,
  "temperature": 23.0
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 17,
  "temperature": 23.5
}

###

# добавление измерения
POST {{baseUrl}}/measurements/
Content-Type: application/json

{
  "sensor": 17,
  "temperature": 22.9
}

###

# получение датчиков
GET {{baseUrl}}/sensors/
Content-Type: application/json

###

# получение информации по датчику
GET {{baseUrl}}/sensors/17/
Content-Type: application/json
