# Generated by Django 5.2.1 on 2025-05-26 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("phones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="phone",
            name="image",
            field=models.CharField(max_length=150),
        ),
    ]
